# Generated by Django 2.0.4 on 2018-07-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('background_image', models.ImageField(blank=True, upload_to='')),
                ('navigation_spritesheet', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('ordering', models.FloatField()),
                ('transcript', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.Comic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('comic', 'slug')},
        ),
    ]
