# Generated by Django 2.0.4 on 2018-07-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
