# Generated by Django 2.0.4 on 2018-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_page_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
