# Generated by Django 2.0.4 on 2018-07-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_page_alt_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='background_image',
            new_name='header_image',
        ),
    ]
