# Generated by Django 2.0.7 on 2018-07-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_auto_20180717_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='overflow_color',
        ),
        migrations.AddField(
            model_name='comic',
            name='background',
            field=models.CharField(default='white', help_text='a valid CSS `background` configuration', max_length=24),
        ),
        migrations.AddField(
            model_name='comic',
            name='overflow',
            field=models.CharField(default='white', help_text='a valid CSS `background` configuration', max_length=24),
        ),
    ]
