# Generated by Django 2.0.7 on 2018-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_auto_20180717_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='background',
            field=models.TextField(default='white', help_text='a valid CSS `background` configuration'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='overflow',
            field=models.TextField(default='white', help_text='a valid CSS `background` configuration'),
        ),
    ]
