# Generated by Django 2.0.7 on 2018-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20180717_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='slug',
            field=models.CharField(default='swords', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
