# Generated by Django 2.0.7 on 2018-08-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_auto_20180805_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='comics.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('comic', 'slug'), ('comic', 'ordering')},
        ),
    ]
