# Generated by Django 2.0.7 on 2018-08-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_auto_20180826_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='font',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
