# Generated by Django 2.1.1 on 2018-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_auto_20180910_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='post_border_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
