# Generated by Django 2.1.1 on 2018-09-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0016_comic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.TextField(blank=True, help_text='Accepts Markdown'),
        ),
        migrations.AlterField(
            model_name='page',
            name='post',
            field=models.TextField(blank=True, help_text='Accepts Markdown'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='comics.Tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcript',
            field=models.TextField(blank=True, help_text='Accepts Markdown'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, help_text='This image needs to be a 1:1 aspect ratio.', null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='tagtype',
            unique_together={('comic', 'title')},
        ),
    ]
