# Generated by Django 2.1.1 on 2018-09-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_auto_20180914_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('ordering',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('type', 'title')},
        ),
        migrations.AlterModelOptions(
            name='tagtype',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='comic',
            name='spinner_image',
            field=models.ImageField(blank=True, help_text='A square image that can spin about its center. Ideally 120x120px.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='comics.Comic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='comics.Comic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='comics.TagType'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_types', to='comics.Comic'),
        ),
    ]
