# Generated by Django 2.1.1 on 2018-10-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0018_auto_20180918_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='comic',
        ),
    ]
