# Generated by Django 2.1.5 on 2019-01-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0021_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='genre',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
