# Generated by Django 2.1.5 on 2019-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0022_comic_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='favicon_image',
            field=models.ImageField(blank=True, help_text='A square PNG to be used as a favicon. Ideally 192x192px.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='comic',
            name='spinner_image',
            field=models.ImageField(blank=True, help_text='A square PNG that can spin about its center. Ideally 120x120px.', upload_to=''),
        ),
    ]
