# Generated by Django 2.2.2 on 2019-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0023_auto_20190507_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='adsense_ad_slot',
            field=models.CharField(blank=True, help_text='Looks like `1234567890`', max_length=10),
        ),
        migrations.AddField(
            model_name='comic',
            name='adsense_publisher_account',
            field=models.CharField(blank=True, help_text='Looks like `pub-1234567891234567`', max_length=32),
        ),
    ]
