# Generated by Django 2.2.2 on 2019-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0024_auto_20190623_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='discourse_url',
            field=models.URLField(blank=True, help_text='Link to a Discourse forum, for example `https://forum.example.com/`'),
        ),
        migrations.AddField(
            model_name='comic',
            name='domain',
            field=models.CharField(blank=True, help_text='The domain used to view this comic, in the format `subdomain.example.com`. If this is blank, the comic will not be able to be viewed.', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.CharField(help_text='Deprecated.', max_length=128, unique=True),
        ),
    ]
