# Generated by Django 2.2.2 on 2019-12-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0025_auto_20191226_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Any request going to this domain will be redirected to the canonical domain of the comic.', max_length=128, unique=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_urls', to='comics.Comic')),
            ],
        ),
    ]
