# Generated by Django 3.0.1 on 2019-12-27 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0026_aliasurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Any request going to this domain will be shown the comic index pages.', max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True, help_text='The ad shown on the page is randomly chosen from all active ads.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ordering',
            field=models.FloatField(help_text='Lower numbers appear first. You can use negative numbers and decimals (eg. -2.5).'),
        ),
        migrations.AlterField(
            model_name='page',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="If this is in the future, it won't be visible until that time."),
        ),
    ]
