# Generated by Django 3.0.1 on 2019-12-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0027_auto_20191227_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
