# Generated by Django 3.0.1 on 2019-12-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0028_comic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(choices=[('overflow-background', 'Overflowbackground')], max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic')),
            ],
            options={
                'unique_together': {('comic', 'property')},
            },
        ),
    ]
