# Generated by Django 3.0.1 on 2019-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0029_styleconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleconfiguration',
            name='property',
            field=models.CharField(choices=[('overflow-background', 'Overflow Background'), ('content-background', 'Content Background'), ('primary-text-color', 'Primary Text Color'), ('font-url', 'Font Url'), ('hr-image-url', 'Hr Image Url'), ('spinner-image-url', 'Spinner Image Url'), ('navigation-spritesheet-url', 'Navigation Spritesheet Url'), ('border-image-url', 'Border Image Url')], max_length=32),
        ),
    ]
