# Generated by Django 3.0.2 on 2020-01-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0032_auto_20200108_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ordering', models.FloatField(help_text='Lower numbers appear first. You can use negative numbers and decimals (eg. -2.5).')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='comics.Comic')),
            ],
            options={
                'ordering': ('ordering',),
                'unique_together': {('comic', 'ordering')},
            },
        ),
    ]
