# Generated by Django 3.0.2 on 2020-01-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0033_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Records the last edit of this Comic.'),
        ),
        migrations.AddField(
            model_name='page',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Records the last edit of this Page.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Records the last edit of this Tag.'),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Records the last edit of this TagType.'),
        ),
    ]
