# Generated by Django 3.0.2 on 2020-01-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0034_auto_20200128_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='overflow_background_image',
            field=models.ImageField(blank=True, help_text='A large JPG. Ideally 2048px wide by 1024px tall or larger.', upload_to=''),
        ),
    ]
