# Generated by Django 3.0.2 on 2020-04-27 15:42

import apps.comics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0035_comic_overflow_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cta_text', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, help_text='This icon should be a 1:1 aspect ratio, and should be in color.', null=True, upload_to=apps.comics.models.social_icon_static_path)),
                ('share_template', models.CharField(blank=True, help_text='Use {url}, {message} for vars', max_length=128)),
                ('follow_template', models.CharField(blank=True, help_text='Use {handle} for vars', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='styleconfiguration',
            name='property',
            field=models.CharField(choices=[('overflow-background', 'Overflow Background'), ('content-background', 'Content Background'), ('primary-text-color', 'Primary Text Color'), ('footer-background-color', 'Footer Background Color'), ('tag-background-color', 'Tag Background Color'), ('tag-text-color', 'Tag Text Color'), ('tab-inactive-color', 'Tab Inactive Color'), ('tab-active-color', 'Tab Active Color'), ('tab-text-color', 'Tab Text Color'), ('spinner-image', 'Spinner Image'), ('navigation-spritesheet', 'Navigation Spritesheet'), ('post-border-image', 'Post Border Image')], help_text="Use CSS property values. For colors, that's like `#000000FF` and for images that's like `url(https://placekitten.com/120/120/)`", max_length=32),
        ),
        migrations.CreateModel(
            name='LinkedSocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, max_length=64)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.SocialPlatform')),
            ],
        ),
    ]
