# Generated by Django 3.0.7 on 2020-06-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0036_auto_20200427_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatform',
            name='visit_template',
            field=models.CharField(blank=True, help_text='Use {handle} for vars.', max_length=128),
        ),
        migrations.AlterField(
            model_name='linkedsocialplatform',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='comics.Comic'),
        ),
        migrations.AlterField(
            model_name='linkedsocialplatform',
            name='handle',
            field=models.CharField(blank=True, help_text='Leave blank if you have no page; it still needs to be connected for people to share to this platform.', max_length=64),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='follow_template',
            field=models.CharField(blank=True, help_text="Use {handle} for vars. Leave blank if it doesn't have explicit follow functionality.", max_length=128),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='share_template',
            field=models.CharField(blank=True, help_text="Use {url}, {message} for vars. Leave blank if it doesn't have share functionality.", max_length=128),
        ),
    ]
