# Generated by Django 3.0.7 on 2020-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0038_auto_20200620_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedsocialplatform',
            old_name='call_to_action',
            new_name='follow_cta',
        ),
        migrations.RenameField(
            model_name='socialplatform',
            old_name='call_to_action',
            new_name='follow_cta',
        ),
        migrations.AddField(
            model_name='linkedsocialplatform',
            name='share_cta',
            field=models.CharField(blank=True, help_text='If not blank, overrides the platform CTA.', max_length=128),
        ),
        migrations.AddField(
            model_name='linkedsocialplatform',
            name='visit_cta',
            field=models.CharField(blank=True, help_text='If not blank, overrides the platform CTA.', max_length=128),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='share_cta',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='socialplatform',
            name='visit_cta',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
