# Generated by Django 3.0.7 on 2020-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0039_auto_20200621_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedsocialplatform',
            name='requires_money',
            field=models.BooleanField(default=False),
        ),
    ]
