# Generated by Django 3.0.7 on 2020-06-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0042_remove_socialplatform_cta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='archive_icon',
            field=models.ImageField(blank=True, help_text='A square PNG to be used as an archive/pages icon.', upload_to=''),
        ),
    ]
