# Generated by Django 3.0.7 on 2020-06-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0043_comic_archive_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='adsense_ad_slot_header',
            field=models.CharField(blank=True, help_text='Looks like `1234567890`', max_length=10),
        ),
    ]
