# Generated by Django 3.1.2 on 2020-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0044_comic_adsense_ad_slot_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='bsa_ad_slot_body',
            field=models.CharField(blank=True, help_text='Looks like `bsa-zone_1234567890123-4_123456`', max_length=64),
        ),
        migrations.AddField(
            model_name='comic',
            name='bsa_ad_slot_header',
            field=models.CharField(blank=True, help_text='Looks like `bsa-zone_1234567890123-4_123456`', max_length=64),
        ),
        migrations.AddField(
            model_name='comic',
            name='bsa_link',
            field=models.URLField(blank=True, help_text='Link to a BuySellAds js script, for example: `https://cdn4.buysellads.net/pub/foo.js`'),
        ),
    ]
