# Generated by Django 3.2.7 on 2021-09-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0047_auto_20210910_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeSnippets',
            new_name='CodeSnippet',
        ),
    ]
