# Generated by Django 3.2.7 on 2021-09-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0048_rename_codesnippets_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Start of Head'), (1, 'End of Body')], default=0, help_text='The location in the document where the code will be injected.'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(blank=True, help_text="The HTML code that is injected into the page. BE CAREFUL -- this code can break your site if you don't know what you are doing!"),
        ),
    ]
