# Generated by Django 3.2.7 on 2021-09-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0049_auto_20210911_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text the user should see. Keep this short!', max_length=24)),
                ('active', models.BooleanField(default=True, help_text='Disable this to remove the injected code from the page.')),
                ('ordering', models.FloatField(default=0, help_text='The order in which the links are shown. Smaller is shown first.')),
                ('url', models.URLField(help_text='The URL you want to send people to.')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='comics.comic')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
