# Generated by Django 3.2.7 on 2021-10-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0050_headerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='comic',
            field=models.ForeignKey(blank=True, help_text='Which comic does this snippet appear on? Leave blank for all comics.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='comics.comic'),
        ),
    ]
