# Generated by Django 3.2.7 on 2021-10-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0051_alter_codesnippet_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='testing',
            field=models.BooleanField(default=False, help_text='When this is active, it is only embedded on the test URL page.'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Start of Head'), (1, 'End of Body'), (2, 'Inside Header Ad Slot'), (3, 'Inside Below Comic Ad Slot')], default=0, help_text='The location in the document where the code will be injected.'),
        ),
    ]
