# Generated by Django 3.2.15 on 2022-08-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0052_auto_20211014_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='quests_tab_title',
            field=models.CharField(default='Quests', max_length=16),
        ),
        migrations.AddField(
            model_name='page',
            name='chronological_ordering',
            field=models.FloatField(default=0, help_text='Lower numbers appear first. You can use negative numbers and decimals (eg. -2.5).'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Start of Head'), (1, 'End of Body'), (2, 'Inside Header Ad Slot'), (3, 'Inside Below Comic Ad Slot'), (4, 'Inside Below Info Ad Slot')], default=0, help_text='The location in the document where the code will be injected.'),
        ),
    ]
