# Generated by Django 3.2.15 on 2022-08-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0053_auto_20220821_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ad_override',
            field=models.ForeignKey(blank=True, help_text='If not blank, this ad will be shown on this tag page. HEADS UP! It will show even if deactivated!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.ad'),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='ad_override',
            field=models.ForeignKey(blank=True, help_text='If not blank, this ad will be shown on this tag page. HEADS UP! It will show even if deactivated!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.ad'),
        ),
    ]
