# Generated by Django 3.2.15 on 2022-08-24 02:29

import apps.comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0055_page_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=apps.comics.models.Page.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended size: 300x300px', null=True, upload_to=apps.comics.models.Page.get_thumbnail_file_path),
        ),
    ]
