# Generated by Django 4.1.1 on 2023-03-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0056_auto_20220824_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('Banner', 'Banner'), ('Popup', 'Popup')], default='Banner', max_length=6),
        ),
    ]
