# Generated by Django 4.1.1 on 2023-03-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0057_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCodeRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(help_text="The uri you want on the comics side, eg. 'patreon'", max_length=24)),
                ('url', models.URLField(help_text='The URL you want to send people to.')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_codes', to='comics.comic')),
            ],
        ),
    ]
