# Generated by Django 4.1.1 on 2023-03-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0058_shortcoderedirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='secret_image',
            field=models.ImageField(blank=True, help_text='Shows up when the user inputs the Konami code', upload_to=''),
        ),
    ]
