# Generated by Django 4.2.1 on 2023-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0060_comic_cloudflare_token_comic_cloudflare_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexUrl',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='adsense_ad_slot',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='adsense_ad_slot_header',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='adsense_publisher_account',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='bsa_ad_slot_body',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='bsa_ad_slot_header',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='bsa_link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='discord_link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='patreon_link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='reddit_link',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='comic',
            name='cloudflare_resize',
            field=models.BooleanField(default=False, help_text="If True, resize images using CloudFlare's API. (Requires paid account.)"),
        ),
    ]
